version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  enable:
    - gocritic
    - misspell
    - revive
  settings:
    errcheck:
      check-blank: true
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gocritic
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/lumberbarons/modbus
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
